name: Synopsys Security Testing

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Synopsys Action
        uses: synopsys-sig/synopsys-action@v1.2.0
        with:
          blackduck_apiToken: MTU1NjczMWQtMjljMS00ZWQ1LWFkYzEtMTgyNzAxNjc3ZmIwOmI2Mzg3MmRiLWFiYTItNDZhOS05MjI2LTNkOGQxZjU3ODk2OQ==
          blackduck_url: https://testing.blackduck.synopsys.com 
          
          #Optional- To enable feedback from Black Duck security testing as pull request comment
          #blackduck_automation_prcomment: true
          #Optional- To enable autoamtic fix pull request creation if vulnerabilities are reported
          blackduck_automation_fixpr: true
          #Mandatory if blackduck_automation_fixpr or blackduck_automation_prcomment is set true
          #github_token: ${{ secrets.GITHUB_TOKEN }}
